package presentation;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import javax.swing.JOptionPane;

import bll.EmployeeBLL;
import model.Employee;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ancuta
 */
public class AdministratorUI extends javax.swing.JFrame {

	BufferedWriter writer;
	BufferedReader objReader;

	/**
	 * Creates new form AdministratorUI
	 */
	public AdministratorUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jTextField6 = new javax.swing.JTextField();
		jButton5 = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jTextField7 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setResizable(false);

		jLabel1.setText("Index:");

		jLabel2.setText("Name:");

		jLabel3.setText("SSN:");

		jLabel4.setText("E-mail:");

		jLabel5.setText("Password:");

		jButton1.setText("CREATE EMPLOYEE");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("RETRIEVE EMPLOYEE");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("UPDATE EMPLOYEE");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("DELETE EMPLOYEE");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setText("GENERATE REPORT");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jLabel6.setText("Enter period start date");
		jLabel7.setText("Enter period end date");

		jButton6.setText("CLEAR FIELDS");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addGroup(layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(layout.createSequentialGroup().addGap(47, 47, 47).addGroup(layout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
												jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 168,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING).addComponent(jButton4,
														javax.swing.GroupLayout.PREFERRED_SIZE, 168,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE,
																168, Short.MAX_VALUE)
														.addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))))
										.addGap(107, 107, 107))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 110,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(27, 27, 27)))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup().addGap(0, 66, Short.MAX_VALUE)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
														.createSequentialGroup().addComponent(jLabel1).addPreferredGap(
																javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
														.addComponent(jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE, 194,
																javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
														.createSequentialGroup().addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.TRAILING)
																.addComponent(jLabel3).addComponent(jLabel2)
																.addComponent(jLabel4).addComponent(jLabel5))
														.addGap(9, 9, 9)
														.addGroup(layout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jTextField2,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 194,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jTextField3,
																		javax.swing.GroupLayout.Alignment.TRAILING,
																		javax.swing.GroupLayout.PREFERRED_SIZE, 194,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 194,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING,
														javax.swing.GroupLayout.PREFERRED_SIZE, 194,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel7).addComponent(jLabel6))
										.addGap(0, 0, Short.MAX_VALUE)))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addGap(36, 36, 36)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jButton6,
												javax.swing.GroupLayout.PREFERRED_SIZE, 45,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel1))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel2))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel3))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4))
										.addGap(18, 18, 18)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel5))))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel6))
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 38,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel7)))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addContainerGap()))));

		pack();
	}// </editor-fold>

	// CREATE EMPLOYEE
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		int index = Integer.parseInt(jTextField1.getText());
		String name = jTextField2.getText();
		String ssn = jTextField3.getText();
		String email = jTextField4.getText();
		;
		String password = jTextField5.getText();

		Employee e = new Employee(index, name, ssn, email, password);
		EmployeeBLL eBLL = new EmployeeBLL();
		@SuppressWarnings("unused")
		int eId = eBLL.create(e);
		JOptionPane.showMessageDialog(null, "The employee with SSN " + ssn + " has been created!");
	}

	// RETRIEVE EMPLOYEE
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		String ssn = jTextField3.getText();
		EmployeeBLL eBLL = new EmployeeBLL();

		Employee e = eBLL.retrieve(ssn);
		jTextField1.setText(String.valueOf(e.getIdEmployee()));
		jTextField2.setText(e.getNameEmployee());
		jTextField4.setText(e.getEmail());
		jTextField5.setText(e.getPassword());

	}

	// UPDATE EMPLOYEE
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		int index = Integer.parseInt(jTextField1.getText());
		String name = jTextField2.getText();
		String ssn = jTextField3.getText();
		String email = jTextField4.getText();
		String password = jTextField5.getText();

		Employee e = new Employee(index, name, ssn, email, password);
		EmployeeBLL eBLL = new EmployeeBLL();
		@SuppressWarnings("unused")
		int eId = eBLL.update(e);
		JOptionPane.showMessageDialog(null, "The employee info has been updated!");
	}

	// DELETE EMPLOYEE
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		String ssn = jTextField3.getText();

		EmployeeBLL eBLL = new EmployeeBLL();
		eBLL.delete(ssn);
		JOptionPane.showMessageDialog(null, "The employee with SSN " + ssn + " has been deleted!");
	}

	// GENERATE REPORT
	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			writer = new BufferedWriter(new FileWriter("Report.txt"));
		} catch (IOException e1) {
			e1.printStackTrace();
		}
		
		String periodStart = jTextField6.getText();
		String periodEnd = jTextField7.getText();
		String strCurrentLine;
		String ssn = jTextField3.getText();
		EmployeeBLL eBLL = new EmployeeBLL();
		Employee e = eBLL.retrieve(ssn);
		
		try {
			
			writer = new BufferedWriter(new FileWriter("Report.txt", true));
			objReader = new BufferedReader(new FileReader("EmployeeActivity.txt"));
			objReader.readLine();
			while ((strCurrentLine = objReader.readLine()) != null) {
				if (!strCurrentLine.endsWith(e.getEmail())) {
					if (strCurrentLine.startsWith(periodEnd)) {
						break;
					} 
				
					System.out.println(strCurrentLine);
					System.out.println(periodStart);
					System.out.println(periodEnd);
				
					if (strCurrentLine.startsWith(periodStart)) {
						writer.append(strCurrentLine);
						writer.newLine();
					} else if (!strCurrentLine.startsWith(periodStart) && !strCurrentLine.startsWith(periodEnd)) {
						writer.append(strCurrentLine);
					}
			} else {
				writer.append("REPORT EMPLOYEE " + e.getNameEmployee());
				writer.newLine();
				writer.newLine();
				writer.append(strCurrentLine);
				writer.newLine();
			}
			}
			writer.close();
		} catch (IOException ex) {
			ex.printStackTrace();
		}
	}

	// CLEAR FIELDS
	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		jTextField1.setText("");
		jTextField2.setText("");
		jTextField3.setText("");
		jTextField4.setText("");
		jTextField5.setText("");
	}

	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	// End of variables declaration
}
