package presentation;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import bll.AccountBLL;
import bll.ClientBLL;
import model.Account;
import model.Client;

/**
 *
 * @author Ancuta
 */
public class FrontDeskEmployeeUI extends javax.swing.JFrame {
	
	DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
	Date date;

	/**
	 * Creates new form EmployeeApp
	 */
	public FrontDeskEmployeeUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jTextField1 = new javax.swing.JTextField();
		jTextField2 = new javax.swing.JTextField();
		jTextField3 = new javax.swing.JTextField();
		jTextField4 = new javax.swing.JTextField();
		jTextField5 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton9 = new javax.swing.JButton();
		jTextField6 = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setMaximumSize(null);
		setResizable(false);

		jButton1.setText("ADD CLIENT");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("UPDATE CLIENT");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("VIEW INFO CLIENT");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jLabel1.setText("ID:");

		jLabel2.setText("Name:");

		jLabel3.setText("Identity Card No:");

		jLabel4.setText("SSN:");

		jLabel5.setText("Address:");

		jButton4.setText("MANAGE ACCOUNTS");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton5.setText("PROCESS UTILITIES BILLS");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton6.setText("MAKE TRANSFERS");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		jTextField6.setText("YES OR NO");

		jLabel6.setText("Utilities provider:");

		jButton7.setText("GET NEXT ID");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jButton8.setText("CLEAR FIELDS");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		jButton9.setText("VIEW CLIENT ACCOUNTS");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(58, 58, 58)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 183,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
												.addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGap(220, 220, 220))
										.addGroup(layout.createSequentialGroup()
												.addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addGap(178, 178, 178)))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(layout.createSequentialGroup().addGroup(layout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel6).addComponent(jLabel2).addComponent(jLabel3)
												.addComponent(jLabel4).addComponent(jLabel5)).addGap(26, 26, 26))
										.addGroup(layout.createSequentialGroup().addComponent(jLabel1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jButton7)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(jTextField1).addComponent(jTextField2)
														.addComponent(jTextField3)
														.addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE,
																155, Short.MAX_VALUE))
												.addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 155,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 155,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(jButton6, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)))
				.addContainerGap(21, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
						.createSequentialGroup().addGap(25, 25, 25).addComponent(jButton1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jButton2)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jButton3)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addContainerGap()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 43,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel1).addComponent(jButton7))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 44,
												Short.MAX_VALUE)
										.addComponent(jLabel2))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel3))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel4))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jLabel5).addComponent(jButton4))))
				.addComponent(jButton5).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jButton6)
						.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 42,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel6))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton8)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jButton9)
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	// ADD CLIENT
	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {

		date = new Date();

		int id = Integer.valueOf(jTextField1.getText());
		String name = jTextField2.getText();
		String idcno = jTextField3.getText();
		String ssn = jTextField4.getText();
		String address = jTextField5.getText();
		String utilitiesProvider = jTextField6.getText();

		Client c = new Client(id, name, idcno, ssn, address, utilitiesProvider);
		ClientBLL cBLL = new ClientBLL();
		int addclient = cBLL.add(c);
		JOptionPane.showMessageDialog(null, "The client info has been added!");
			
		CreateFile output = new CreateFile();
		output.appendToFileAndClose(dateFormat.format(date) + " ADD CLIENT \n");

	}

	// UPDATE CLIENT
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		date = new Date();
		
		int id = Integer.valueOf(jTextField1.getText());
		String name = jTextField2.getText();
		String idcno = jTextField3.getText();
		String ssn = jTextField4.getText();
		String address = jTextField5.getText();
		String utilitiesProvider = jTextField6.getText();

		Client c = new Client(id, name, idcno, ssn, address, utilitiesProvider);
		ClientBLL cBLL = new ClientBLL();
		int updateClient = cBLL.update(c);
		JOptionPane.showMessageDialog(null, "The client info has been updated!");
		
		CreateFile output = new CreateFile();
		output.appendToFileAndClose(dateFormat.format(date) + " UPDATE CLIENT\n");

	}

	// VIEW INFO CLIENT
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {

		date = new Date();
		String ssn = jTextField4.getText();

		ClientBLL cBLL = new ClientBLL();
		Client c = cBLL.viewInfo(ssn);

		jTextField1.setText(String.valueOf(c.getIdClient()));
		jTextField2.setText(String.valueOf(c.getName()));
		jTextField3.setText(String.valueOf(c.getIdentityCardNo()));
		jTextField5.setText(String.valueOf(c.getAddress()));
		jTextField6.setText(String.valueOf(c.getUtilitiesProvider()));
		
		CreateFile output = new CreateFile();
		output.appendToFileAndClose(dateFormat.format(date) + " VIEW INFO CLIENT\n");
	}

	// MANAGE ACCOUNTS
	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		date = new Date();
		
		new EmployeeAccountUI().setVisible(true);
		CreateFile output = new CreateFile();
		output.appendToFileAndClose(dateFormat.format(date) + " MANAGE ACCOUNTS\n");
	}

	// PROCESS UTILITIES BILLS
	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		new UtilitiesUI().setVisible(true);
	}

	// MAKE TRANSFERS
	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		new TransfersUI().setVisible(true);
	}

	// GET NEXT ID
	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		ClientBLL cBLL = new ClientBLL();
		int lastId = cBLL.lastId();

		jTextField1.setText(String.valueOf(lastId + 1));
	}

	// CLEAR FIELDS
	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {

		jTextField1.setText("");
		jTextField2.setText("");
		jTextField3.setText("");
		jTextField4.setText("");
		jTextField5.setText("");
		jTextField6.setText("");
	}

	// VIEW CLIENT ACCOUNTS
	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		String ssn = jTextField4.getText();
		AccountBLL aBLL = new AccountBLL();

		List<Account> list = aBLL.findAll(ssn);
		List<String> listAccNo = new ArrayList<String>();
		for (Account acc : list) {
			listAccNo.add(acc.getAccountNumber());
		}

		String accNumbers = "";
		for (String accNo : listAccNo) {
			accNumbers += accNo;
			accNumbers += "\n";
		}

		JOptionPane.showMessageDialog(null,
				"The client with SSN: " + ssn + " has the following accounts:\n\n" + accNumbers);
	}


	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	// End of variables declaration
}
